//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dualverse.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dualverse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Dualverse について に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutForm {
            get {
                return ResourceManager.GetString("AboutForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dualverse について(&amp;A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("AboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(&amp;X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExitToolStripMenuItem {
            get {
                return ResourceManager.GetString("ExitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル(&amp;F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileToolStripMenuItem {
            get {
                return ResourceManager.GetString("FileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dualverseがメニューやメッセージを表示する際の言語を選択します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LanguageDescriptionLabel {
            get {
                return ResourceManager.GetString("LanguageDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソースコードを取得 (GitHub) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LinkLabel {
            get {
                return ResourceManager.GetString("LinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再読み込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReloadButton {
            get {
                return ResourceManager.GetString("ReloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceButton {
            get {
                return ResourceManager.GetString("ServiceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既定のサービス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceLabel {
            get {
                return ResourceManager.GetString("ServiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左ペイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceLeftLabel {
            get {
                return ResourceManager.GetString("ServiceLeftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右ペイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceRightLabel {
            get {
                return ResourceManager.GetString("ServiceRightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsToolStripMenuItem {
            get {
                return ResourceManager.GetString("SettingsToolStripMenuItem", resourceCulture);
            }
        }
    }
}
